### ISSUE TITLE
Need to handle with try/except on user blocking

### ISSUE THREAD

**Issue by kasaiee** [o3o3o/django-graphql-ratelimit#1]
Hi, thanks for the project.
I need to raise an error when the user blocked.
how can I do this?

**Comment by o3o3o** [comment]
@kasaiee  
It has already raised an exception [here](https://github.com/o3o3o/django-graphql-ratelimit/blob/d9f127d9641c19a73bc120f482f400cfdc3b8df3/django_graphql_ratelimit/ratelimit.py#L50).
The code is copied from [djanog-ratelimit](https://github.com/jsocol/django-ratelimit/blob/b300136651172c4edbaf278473996789d8a3ae02/ratelimit/decorators.py#L23).

The exception:  `Ratelimited` is inherited from `django.core.exceptions.PermissionDenied`.

So may you catch the `Ratelimited`  exception in a middleware?

**Comment by o3o3o** [comment]
Feel free to reopen this issue if you still have problems.
