### ISSUE TITLE
Set rate limit for Django-graphql-jwt custom token auth mutation.

### ISSUE THREAD

**Issue by Satosh-J** [o3o3o/django-graphql-ratelimit#3]
```
from django_graphql_ratelimit import ratelimit
from django.utils.decorators import method_decorator

class CustomTokenAuth(ObtainJSONWebToken):

    @classmethod
    @method_decorator(ratelimit(key='gql:username', rate='0/s', block=True))
    def resolve(cls, root, info, **kwargs):

        user = info.context.user
        role = user.profile.role
        logger.info('USER_LOGIN: %s', user)

        if role == 'student':
            student = user.student
            student.check_login_permission()

        user.last_login = timezone.now()
        user.save()

        return cls()


class Mutation(
    api.schema.Mutation,
    # other mutations ...
):
    token_auth = CustomTokenAuth.Field()
```

I want to set api rate limit for graphql-jwt tokenAuth mutation to prevent brute-force attack.
I set cache backend correctly and verified it's working.
![image](https://github.com/o3o3o/django-graphql-ratelimit/assets/95545435/a9384577-28da-462f-b149-32be1c7fe52b)
But, this does not limit api request rate.

Is there any solution to set API request limit for graphql tokenAuth mutation?

**Comment by o3o3o** [comment]
@Satosh-J  I think your setting rate='0/s'  means NO RATE LIMIT according to  [djanog-ratelimit doc](https://django-ratelimit.readthedocs.io/en/stable/rates.html#)

Could you test by rates with `rate=1/m'?

**Comment by o3o3o** [comment]
Hi, @Satosh-J
Could you take a test  with `rate=1/m`, and test the normal `GET` or `POST` with [django-ratelimit](https://django-ratelimit.readthedocs.io/en/stable/installation.html#). 

Mutation should be working here, there is a test case [here](https://github.com/o3o3o/django-graphql-ratelimit/blob/61311756f48cb37781474d5563fa78ad19fcdb5c/django_graphql_ratelimit/tests.py#L24).

**Comment by Satosh-J** [comment]
When I tested it with normal query, the rate limit is working.
![img_20231226(2)](https://github.com/o3o3o/django-graphql-ratelimit/assets/95545435/1edab2ba-68e7-4eb1-b045-101a687f10d3)
![img_20231226(3)](https://github.com/o3o3o/django-graphql-ratelimit/assets/95545435/9a03c0cc-ae53-4cf2-be35-4a49b49994b8)
```

class Query(graphene.ObjectType):
    whoami = graphene.Field(WhoamiInput)

    @login_required
    @ratelimit(key="user_or_ip", rate="3/m", block=True)
    def resolve_whoami(root, info, **kwargs):

        user = info.context.user
        # my own logic
```
If I send the request more than 3 times a minute, it blocks the api request.

**Comment by Satosh-J** [comment]
![img_20231226(4)](https://github.com/o3o3o/django-graphql-ratelimit/assets/95545435/77b9cd66-a59e-484f-8420-16608b951c1e)
```
class CustomTokenAuth(graphql_jwt.JSONWebTokenMutation):

    @classmethod
    @method_decorator(ratelimit(key='gql:password', rate='5/m', block=True))
    def resolve(cls, root, info, **kwargs):
        print(info.context)
        return cls()
```

But, when I use it for tokenAuth mutation, I get the following error.

**Comment by Satosh-J** [comment]
```
class CustomTokenAuth(graphql_jwt.JSONWebTokenMutation):

    @classmethod
    @method_decorator(ratelimit(key='ip', rate='5/m', block=True))
    def resolve(cls, root, info, **kwargs):
        print(info.context)
        return cls()

```

I updated the tokenAuth custom mutation like above code, but this is not working correctly.

That limits the api if only I use correct credentials 5 times a minute.. but when I use incorrect credentials it never blocks the api request.

![img_20231226(5)](https://github.com/o3o3o/django-graphql-ratelimit/assets/95545435/e9d983f7-131a-4424-88e6-59f7e96a1930)
![img_20231226(6)](https://github.com/o3o3o/django-graphql-ratelimit/assets/95545435/38a908ab-2ff4-4086-86b6-8a170a36389c)


The purpose of this package is to prevent brute-force attack, but in this case instead of blocking same api request which is over the limit, it allows same request forever..

Any other solution on this?

**Comment by o3o3o** [comment]
Could you use `@ratelimit(key='ip', rate='5/m', block=True)`  instead of  `@method_decorator(ratelimit(key='ip', rate='5/m', block=True))`?

**Comment by o3o3o** [comment]
you can add more ratelimit on that, like this
  ```
  ...
  @method_decorator(ratelimit(key='gql:username', rate='5/m', block=True))
  @method_decorator(ratelimit(key='ip', rate='5/m', block=True))
   def resolve(cls, root, info, **kwargs):
   ....
   ```

**Comment by Satosh-J** [comment]
There was an issue with my Authentication backend.
```
AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
    'app.backends.RateLimitedLCustomBackend', #Added this custom backend
]
```

Figured out the problem with **django-ratelimit-backend** package.
And the graphql-rate-limit works after the authentication is succeed!
